---
controller_groups:
  - name: "overcloud_Compute"
    description: ""
    inventory: "cloud14a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir14a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: 6bfc119d-c485-418c-9a64-55f6d2e42fbe
      serial: '1'
      tripleo_role_name: Compute
      tripleo_role_networks:
      - ctlplane
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud14a-compute-std-0
      - cloud14a-compute-std-1
      - cloud14a-compute-std-10
      - cloud14a-compute-std-11
      - cloud14a-compute-std-12
      - cloud14a-compute-std-13
      - cloud14a-compute-std-14
      - cloud14a-compute-std-15
      - cloud14a-compute-std-16
      - cloud14a-compute-std-17
      - cloud14a-compute-std-18
      - cloud14a-compute-std-19
      - cloud14a-compute-std-2
      - cloud14a-compute-std-20
      - cloud14a-compute-std-21
      - cloud14a-compute-std-22
      - cloud14a-compute-std-23
      - cloud14a-compute-std-24
      - cloud14a-compute-std-25
      - cloud14a-compute-std-26
      - cloud14a-compute-std-27
      - cloud14a-compute-std-28
      - cloud14a-compute-std-3
      - cloud14a-compute-std-4
      - cloud14a-compute-std-5
      - cloud14a-compute-std-6
      - cloud14a-compute-std-7
      - cloud14a-compute-std-8
      - cloud14a-compute-std-9
    children:
      []
  - name: "overcloud_Controller"
    description: ""
    inventory: "cloud14a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir14a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: 6bfc119d-c485-418c-9a64-55f6d2e42fbe
      serial: '1'
      tripleo_role_name: Controller
      tripleo_role_networks:
      - ctlplane
      - external
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud14a-controller-0
      - cloud14a-controller-1
      - cloud14a-controller-2
    children:
      []
  - name: "overcloud_allovercloud"
    description: ""
    inventory: "cloud14a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir14a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      container_cli: podman
      ctlplane_vip: 10.232.52.190
      external_vip: 10.210.212.205
      internal_api_vip: 10.232.52.13
      redis_vip: 10.232.52.14
      storage_mgmt_vip: 10.232.55.139
      storage_vip: 10.232.53.139
    hosts:
      []
    children:
      - overcloud_Compute
      - overcloud_Controller
  - name: "Compute"
    description: ""
    inventory: "cloud14a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir14a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Compute
  - name: "Controller"
    description: ""
    inventory: "cloud14a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir14a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Controller
  - name: "overcloud"
    description: ""
    inventory: "cloud14a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir14a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_allovercloud
...