---
controller_groups:
  - name: "overcloud_Compute"
    description: ""
    inventory: "cloud7b"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir7b -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: feed3c2b-6b13-44dc-9d07-24f5ea430448
      serial: '1'
      tripleo_role_name: Compute
      tripleo_role_networks:
      - ctlplane
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud7b-compute-std-0
      - cloud7b-compute-std-1
      - cloud7b-compute-std-10
      - cloud7b-compute-std-11
      - cloud7b-compute-std-12
      - cloud7b-compute-std-13
      - cloud7b-compute-std-14
      - cloud7b-compute-std-15
      - cloud7b-compute-std-16
      - cloud7b-compute-std-17
      - cloud7b-compute-std-18
      - cloud7b-compute-std-19
      - cloud7b-compute-std-2
      - cloud7b-compute-std-20
      - cloud7b-compute-std-21
      - cloud7b-compute-std-22
      - cloud7b-compute-std-23
      - cloud7b-compute-std-24
      - cloud7b-compute-std-25
      - cloud7b-compute-std-26
      - cloud7b-compute-std-27
      - cloud7b-compute-std-28
      - cloud7b-compute-std-29
      - cloud7b-compute-std-3
      - cloud7b-compute-std-30
      - cloud7b-compute-std-31
      - cloud7b-compute-std-4
      - cloud7b-compute-std-5
      - cloud7b-compute-std-6
      - cloud7b-compute-std-7
      - cloud7b-compute-std-8
      - cloud7b-compute-std-9
    children:
      []
  - name: "overcloud_Controller"
    description: ""
    inventory: "cloud7b"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir7b -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: feed3c2b-6b13-44dc-9d07-24f5ea430448
      serial: '1'
      tripleo_role_name: Controller
      tripleo_role_networks:
      - ctlplane
      - external
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud7b-controller-0
      - cloud7b-controller-1
      - cloud7b-controller-2
    children:
      []
  - name: "overcloud_allovercloud"
    description: ""
    inventory: "cloud7b"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir7b -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      container_cli: podman
      ctlplane_vip: 10.150.144.26
      external_vip: 10.150.150.136
      internal_api_vip: 10.150.151.10
      redis_vip: 10.150.151.11
      storage_mgmt_vip: 10.150.152.10
      storage_vip: 10.150.151.135
    hosts:
      []
    children:
      - overcloud_Compute
      - overcloud_Controller
  - name: "Compute"
    description: ""
    inventory: "cloud7b"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir7b -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Compute
  - name: "Controller"
    description: ""
    inventory: "cloud7b"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir7b -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Controller
  - name: "overcloud"
    description: ""
    inventory: "cloud7b"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir7b -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_allovercloud
...