---
controller_groups:
  - name: "overcloud_Compute"
    description: ""
    inventory: "cloud10a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir10a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: 233cfefd-baf9-47d2-8519-6a9999139e2c
      serial: '1'
      tripleo_role_name: Compute
      tripleo_role_networks:
      - ctlplane
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud10a-compute-std-0
      - cloud10a-compute-std-1
      - cloud10a-compute-std-10
      - cloud10a-compute-std-11
      - cloud10a-compute-std-12
      - cloud10a-compute-std-13
      - cloud10a-compute-std-14
      - cloud10a-compute-std-15
      - cloud10a-compute-std-16
      - cloud10a-compute-std-17
      - cloud10a-compute-std-18
      - cloud10a-compute-std-19
      - cloud10a-compute-std-2
      - cloud10a-compute-std-20
      - cloud10a-compute-std-21
      - cloud10a-compute-std-22
      - cloud10a-compute-std-23
      - cloud10a-compute-std-24
      - cloud10a-compute-std-25
      - cloud10a-compute-std-26
      - cloud10a-compute-std-27
      - cloud10a-compute-std-28
      - cloud10a-compute-std-3
      - cloud10a-compute-std-4
      - cloud10a-compute-std-5
      - cloud10a-compute-std-6
      - cloud10a-compute-std-7
      - cloud10a-compute-std-8
      - cloud10a-compute-std-9
    children:
      []
  - name: "overcloud_Controller"
    description: ""
    inventory: "cloud10a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir10a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: 233cfefd-baf9-47d2-8519-6a9999139e2c
      serial: '1'
      tripleo_role_name: Controller
      tripleo_role_networks:
      - ctlplane
      - external
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud10a-controller-0
      - cloud10a-controller-1
      - cloud10a-controller-2
    children:
      []
  - name: "overcloud_allovercloud"
    description: ""
    inventory: "cloud10a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir10a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      container_cli: podman
      ctlplane_vip: 10.232.100.51
      external_vip: 10.32.132.138
      internal_api_vip: 10.232.87.13
      redis_vip: 10.232.87.14
      storage_mgmt_vip: 10.150.134.11
      storage_vip: 10.150.133.11
    hosts:
      []
    children:
      - overcloud_Compute
      - overcloud_Controller
  - name: "Compute"
    description: ""
    inventory: "cloud10a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir10a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Compute
  - name: "Controller"
    description: ""
    inventory: "cloud10a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir10a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Controller
  - name: "overcloud"
    description: ""
    inventory: "cloud10a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir10a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_allovercloud
...