---
controller_groups:
  - name: "overcloud_Compute"
    description: ""
    inventory: "cloud15a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir15a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: 01c87ade-f52a-461d-a805-aeb842f10e5a
      serial: '1'
      tripleo_role_name: Compute
      tripleo_role_networks:
      - ctlplane
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud15a-compute-std-0
      - cloud15a-compute-std-1
      - cloud15a-compute-std-10
      - cloud15a-compute-std-11
      - cloud15a-compute-std-12
      - cloud15a-compute-std-13
      - cloud15a-compute-std-14
      - cloud15a-compute-std-15
      - cloud15a-compute-std-16
      - cloud15a-compute-std-17
      - cloud15a-compute-std-18
      - cloud15a-compute-std-19
      - cloud15a-compute-std-2
      - cloud15a-compute-std-20
      - cloud15a-compute-std-21
      - cloud15a-compute-std-22
      - cloud15a-compute-std-23
      - cloud15a-compute-std-24
      - cloud15a-compute-std-25
      - cloud15a-compute-std-26
      - cloud15a-compute-std-27
      - cloud15a-compute-std-28
      - cloud15a-compute-std-29
      - cloud15a-compute-std-3
      - cloud15a-compute-std-4
      - cloud15a-compute-std-5
      - cloud15a-compute-std-6
      - cloud15a-compute-std-7
      - cloud15a-compute-std-8
      - cloud15a-compute-std-9
    children:
      []
  - name: "overcloud_Controller"
    description: ""
    inventory: "cloud15a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir15a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      bootstrap_server_id: 01c87ade-f52a-461d-a805-aeb842f10e5a
      serial: '1'
      tripleo_role_name: Controller
      tripleo_role_networks:
      - ctlplane
      - external
      - internal_api
      - storage
      - storage_mgmt
      - storage_nfs
      - tenant
    hosts:
      - cloud15a-controller-0
      - cloud15a-controller-1
      - cloud15a-controller-2
    children:
      []
  - name: "overcloud_allovercloud"
    description: ""
    inventory: "cloud15a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir15a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
      container_cli: podman
      ctlplane_vip: 10.232.134.161
      external_vip: 10.232.137.9
      internal_api_vip: 10.232.134.12
      redis_vip: 10.232.134.13
      storage_mgmt_vip: 10.150.146.4
      storage_vip: 10.150.141.134
    hosts:
      []
    children:
      - overcloud_Compute
      - overcloud_Controller
  - name: "Compute"
    description: ""
    inventory: "cloud15a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir15a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Compute
  - name: "Controller"
    description: ""
    inventory: "cloud15a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir15a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_Controller
  - name: "overcloud"
    description: ""
    inventory: "cloud15a"
    variables:
      ansible_ssh_common_args: -o ProxyJump=awx@ieatrheldir15a -o StrictHostKeyChecking=no
      ansible_ssh_user: awx
    hosts:
      []
    children:
      - overcloud_allovercloud
...