---
controller_templates:
  - name: "Check Compute logs"
    description: ""
    organization: "DE"
    project: "stackcentric-internal"
    playbook: "supportlogs/search_compute_logs.yaml"
    job_type: "run"
    fact_caching_enabled: "False"
    credentials:
      - "awx_ssh"
    concurrent_jobs_enabled: "False"
    ask_scm_branch_on_launch: "False"
    ask_tags_on_launch: "False"
    ask_inventory_on_launch: true
    ask_limit_on_launch: true
    ask_verbosity_on_launch: "False"
    ask_variables_on_launch: "True"
    execution_environment: "awx-base"
    survey_enabled: False
    survey_spec: {}
...
