---
controller_templates:
  - name: "Check Controller Logs"
    description: ""
    organization: "DE"
    project: "stackcentric-internal"
    playbook: "supportlogs/search_controller_logs.yaml"
    job_type: "run"
    fact_caching_enabled: "False"
    concurrent_jobs_enabled: "False"
    ask_scm_branch_on_launch: "False"
    ask_tags_on_launch: "False"
    ask_verbosity_on_launch: "False"
    ask_inventory_on_launch: "True"
    ask_variables_on_launch: "True"
    execution_environment: "awx-base"
    survey_enabled: False
    survey_spec: {}
...
