---
controller_templates:
  - name: "Deploy VyOS VMs"
    description: ""
    organization: "DE"
    project: "infra-baremetal"
    inventory: "awx_local"
    playbook: "deploy_vyos.yml"
    job_type: "run"
    fact_caching_enabled: "False"
    credentials:
      - "deployment_password"
    concurrent_jobs_enabled: "False"
    ask_scm_branch_on_launch: "False"
    ask_tags_on_launch: "False"
    ask_verbosity_on_launch: "False"
    ask_variables_on_launch: "False"
    execution_environment: "vmware-ee"
    survey_enabled: True
    survey_spec:
      description: ''
      name: ''
      spec:
      - question_name: Select the network pod for the VyOS VMs
        question_description: ''
        required: true
        type: multiplechoice
        variable: pod
        new_question: true
        choices: 
          - p0
          - p121
      - question_name: Enter the hostname of the first VyOS VM
        question_description: 'For example: ieatp121vyos007. The hostname should be
          defined in DNS'
        required: true
        type: text
        variable: vyos_vm1
        new_question: true
      - question_name: Enter the hostname for the second VyOS VM
        question_description: 'For example: ieatp121vyos008. The hostname must be
          defined in DNS'
        required: true
        type: text
        variable: vyos_vm2
      - question_name: Enter the cloud name
        question_description: The cloud name, e.g. cloud16b, which will use these
          VyOS VMs.
        required: true
        type: text
        variable: cloud
        new_question: true
      - question_name: Enter the northbound/transport VLAN name
        question_description: northbound/transport VLAN name must match the portgroup
          name in vCenter
        required: true
        type: text
        variable: northbound_vlan_name
        new_question: true
      - question_name: Enter the northbound/transport VLAN ID
        question_description: northbound/transport VLAN ID must match the VLAN ID
          of the portgroup in vCenter
        required: true
        type: text
        variable: northbound_vlan_id
        new_question: true
