---
controller_templates:
  - name: "Generate RC Files"
    description: "Generate RC files on meteo prod server"
    organization: "DE"
    project: "stackcentric-internal"
    inventory: "meteo_prod"
    playbook: "playbooks/generate_rc_files.yml"
    job_type: "run"
    fact_caching_enabled: "False"
    credentials:
      - "awx_ssh"
    concurrent_jobs_enabled: "False"
    ask_scm_branch_on_launch: "False"
    ask_tags_on_launch: "False"
    ask_verbosity_on_launch: "False"
    ask_variables_on_launch: "True"
    execution_environment: "awx-base"
    survey_enabled: False
    survey_spec: {}
...
