---
controller_templates:
  - name: "Add AWX's SSH public key to authorized_keys"
    description: ""
    organization: "DE"
    project: "infra-baremetal"
    playbook: "setup_pwd_free_ssh.yml"
    job_type: "run"
    fact_caching_enabled: "False"
    concurrent_jobs_enabled: "False"
    ask_scm_branch_on_launch: "False"
    ask_tags_on_launch: "False"
    ask_verbosity_on_launch: "False"
    ask_variables_on_launch: "False"
    ask_inventory_on_launch: "True"
    execution_environment: "awx-base"
    survey_enabled: True
    survey_spec:
      description: ''
      name: ''
      spec:
        - question_name: Enter the inventory hostname or host group name
          question_description: Enter the hostname or host group name of the servers
            to be configured with password free SSH. The hostname/host group name must
            match a host from the inventory.
          required: true
          type: text
          variable: group_to_update
        - question_name: 'Username:'
          question_description: User to have their authorized_keys file updated
          required: true
          type: text
          variable: user
        - question_name: 'Enter the password used to access the host(s):'
          question_description: ''
          choices: ''
          default: ''
          max: 32
          min: 0
          new_question: true       
          required: true
          type: password
          variable: ssh_password
...
